// Copyright (c) Wojciech Figat. All rights reserved.

#pragma once

#include "Engine/Core/Types/String.h"

/// <summary>
/// In-process lease that prevents artifact-store cleanup while generated bytes are in use.
/// </summary>
struct FLAXENGINE_API ArtifactLease
{
private:
    String _path;

    explicit ArtifactLease(const StringView& path);
    static void AddRef(const StringView& path);
    static void RemoveRef(const StringView& path);

public:
    ArtifactLease() = default;
    ArtifactLease(const ArtifactLease& other);
    ArtifactLease(ArtifactLease&& other) noexcept;
    ~ArtifactLease();

    ArtifactLease& operator=(const ArtifactLease& other);
    ArtifactLease& operator=(ArtifactLease&& other) noexcept;

    /// <summary>Acquires a lease for an artifact storage path.</summary>
    static ArtifactLease Acquire(const StringView& path);

    /// <summary>Returns the active lease count for an exact storage path.</summary>
    static int32 GetCount(const StringView& path);

    /// <summary>Returns true if the exact storage path is leased.</summary>
    static bool IsLeased(const StringView& path);

    /// <summary>Returns true if the path or any child path is leased.</summary>
    static bool HasLeaseWithin(const StringView& path);

    /// <summary>Deletes a file while excluding concurrent lease acquisition. Returns true on delete failure.</summary>
    static bool DeleteFileIfUnleased(const StringView& path, bool& wasLeased);

    /// <summary>Releases this lease immediately.</summary>
    void Reset();

    bool IsValid() const
    {
        return _path.HasChars();
    }

    StringView GetPath() const
    {
        return _path;
    }
};
