// Copyright (c) Wojciech Figat. All rights reserved.

#pragma once

#include "ArtifactKey.h"
#include "Engine/Content/AssetDatabase/AssetPath.h"
#include "Engine/Content/AssetInfo.h"

/// <summary>Physical storage category selected for an asset load.</summary>
enum class ArtifactStorageKind : byte
{
    Generated,
    Package,
};

/// <summary>Resolver-facing disposition of selected generated bytes.</summary>
enum class ArtifactLoadDisposition : byte
{
    Ready,
    RebuildRequired,
};

/// <summary>Resolved physical bytes for one asset output.</summary>
struct FLAXENGINE_API ResolvedArtifact
{
    Guid AssetID;
    String TypeName;
    ArtifactStoragePath StoragePath;
    String OutputKind;
    String Key;
    ContentHash Content;
    uint64 Size = 0;
    ArtifactStorageKind StorageKind = ArtifactStorageKind::Package;
    bool IsExact = true;
    bool IsLastGood = false;

    static ResolvedArtifact Package(const AssetInfo& info);
    bool IsGenerated() const;
};

/// <summary>Canonical asset identity plus the distinct physical bytes used to load it.</summary>
struct FLAXENGINE_API AssetLoadLocation
{
    AssetInfo Info;
    ResolvedArtifact Artifact;

    static AssetLoadLocation Package(const AssetInfo& info);
};
